import { AnchorProvider, Program, Idl } from "@coral-xyz/anchor";
import { Connection, PublicKey } from "@solana/web3.js";
import { PROGRAM_ID } from "./constants";

let _idl: Idl | null = null;

export async function loadIdl(): Promise<Idl | null> {
  if (_idl) return _idl;
  try {
    // IDL is generated by `anchor build` into target/idl/blockpoly.json.
    // Wrapped in eval to avoid static analysis at build time.
    // eslint-disable-next-line no-new-func
    const dynamicImport = new Function("path", "return import(path)");
    const idlModule = await dynamicImport("../../../target/idl/blockpoly.json");
    _idl = (idlModule.default ?? idlModule) as Idl;
    return _idl;
  } catch {
    console.warn("IDL not found — run `anchor build` to generate it.");
    return null;
  }
}

export function getProgram(provider: AnchorProvider, idl: Idl): Program {
  return new Program(idl, provider);
}

export function createConnection(rpcUrl?: string): Connection {
  const url =
    rpcUrl ??
    process.env.NEXT_PUBLIC_RPC_URL ??
    "https://api.devnet.solana.com";
  return new Connection(url, {
    commitment: "confirmed",
    wsEndpoint: url.replace("https://", "wss://").replace("http://", "ws://"),
  });
}

export const PROGRAM_PUBLIC_KEY = new PublicKey(PROGRAM_ID);
